openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for finding all users
paths:
 /api/signin:
   post:
      tags:
        - Session
      description: API to signin a user
      summary: Searches for user in the database and signs in.
      requestBody:
       required: true
       content:
         application/json:
            schema:
              required:
                - email
                - password
              properties:
               email:
                 type: string
               password:
                 type: string
      responses:
        '200':
          description: Query successful
        '500':
          description: Internal server error
        '501':
          description: MongoDB Exception